apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: eks-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./test
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-gitops
  validation: client
